export const movies = [
  'Titanic',
  'El Rey León',
  'Toy Story',
  'Coco',
  'Frozen',
  'Buscando a Nemo',
  'Shrek',
  'Avatar',
  'Matrix',
  'El Padrino',
  'Volver al Futuro',
  'Jurassic Park',
  'Forrest Gump',
  'El Señor de los Anillos',
  'Harry Potter',
  'Star Wars',
  'Joker',
  'Batman',
  'El Hombre Araña',
  'Iron Man',
  'Los Vengadores',
  'Capitán América',
  'Thor',
  'La Mujer Maravilla',
  'Encanto',
  'Moana',
  'Intensamente',
  'Cars',
  'Ratatouille',
  'WALL-E',
  'Los Increíbles',
  'Monsters Inc',
  'Up',
  'La Bella y la Bestia',
  'La Sirenita',
  'Aladdín',
  'Cenicienta',
  'Mulán',
  'El Libro de la Selva',
  'Roma',
  'Amores Perros',
  'Y Tu Mamá También',
  'El Laberinto del Fauno',
  'Relatos Salvajes',
  'El Secreto de sus Ojos',
  'Nueve Reinas',
  'Diarios de Motocicleta',
  'Ciudad de Dios',
  'Bohemian Rhapsody',
  'Rápidos y Furiosos',
  'Buscando a Dory',
  'Soul',
  'Luca',
  'Valiente',
  'Enredados',
  'Ralph el Demoledor',
  'Grandes Héroes',
  'Zootopia',
  'Red',
  'Lightyear',
  'Pinocho',
  '101 Dálmatas',
  'Dumbo',
  'Bambi',
  'Tiempos Violentos',
  'El Origen',
  'Interestelar',
  'Tenet',
  'Memento',
  'El Caballero de la Noche',
  'Blade Runner',
  'El Octavo Pasajero',
  'Depredador',
  'Terminator',
  'Mad Max',
  'Doctor Strange',
  'Viuda Negra',
  'Hulk',
  'Ant-Man',
  'Deadpool',
  'Guardianes de la Galaxia',
  'Pantera Negra',
  'Aquaman',
  'James Bond',
  'Misión Imposible',
  'John Wick',
  'Transformers',
  'Indiana Jones',
  'E.T. el Extraterrestre',
  'Tiburón',
  'Psicosis',
  'El Exorcista',
  'El Resplandor',
  'Halloween',
  'El Juego del Miedo',
  'It',
  'Mi Pobre Angelito',
  'Loco por Mary',
  'Una Esposa de Mentira',
  'Ricky Bobby',
  'Diario de una Pasión',
  'Crepúsculo',
  '50 Sombras de Grey',
  'Bridget Jones',
  'Mujer Bonita',
  'Ghost',
  'Dirty Dancing',
  'Anastasia',
  'El Príncipe de Egipto',
  'Madagascar',
  'La Era de Hielo',
  'Kung Fu Panda',
  'Cómo Entrenar a tu Dragón',
  'Río',
  'Hotel Transilvania',
  'La La Land',
  'Mamma Mia',
  'Grease',
  'Chicago',
  'Moulin Rouge',
  'Sonrisas y Lágrimas',
  'Rescatando al Soldado Ryan',
  'La Lista de Schindler',
  'El Pianista',
  'Apocalipsis Ahora',
  'Pelotón',
  '1917',
  'Dunkerque',
  'Rocky',
  'Million Dollar Baby',
  'Rambo',
  'El Viaje de Chihiro',
  'Mi Vecino Totoro',
  'La Princesa Mononoke',
  'Volver',
  'Todo Sobre mi Madre',
  'El Hijo de la Novia',
  'La Historia Oficial',
  'Camila',
  'Ocho Apellidos Vascos',
  'Coraline',
  'El Extraño Mundo de Jack',
  'Bichos',
  'Avengers: Endgame',
  'Logan',
  'Cuenta Conmigo',
  'La Vida es Bella',
  'Cinema Paradiso',
  'Amelie',
  'Trainspotting',
  'El Club de la Pelea',
  'Mar Adentro',

  // Disney / Pixar / Animación clásica
  'Tarzán',
  'Hércules',
  'Pocahontas',
  'El Jorobado de Notre Dame',
  'El Planeta del Tesoro',
  'Atlantis: El Imperio Perdido',
  'Hermano Oso',
  'Vacas Vaqueras',
  'Bolt',
  'La Princesa y el Sapo',
  'Lilo y Stitch',
  'Spirit: El Corcel Indomable',
  'Onward: Unidos',
  'Wonka',
  'Migración',
  'La Familia Mitchell vs. Las Máquinas',
  'Spider-Man: A Través del Spider-Verso',
  'Vaiana 2',

  // Otras animaciones populares
  'Bee Movie',
  'El Espantatiburones',
  'Hormiguitas',
  'El Camino a El Dorado',
  'Sinbad: La Leyenda de los Siete Mares',
  'Mi Villano Favorito',
  'Los Minions',
  'Sing: Ven y Canta',
  'La Vida Secreta de Tus Mascotas',
  'Trolls',
  'El Bebé Jefazo',
  'La Gran Aventura LEGO',
  'Lego Batman: La Película',
  'Klaus',
  'Las Aventuras de Tintín',
  'ParaNorman',
  'Frankenweenie',
  'Robots',
  'Rango',
  'Megamente',
  'Lluvia de Hamburguesas',

  // Studio Ghibli / Anime
  'El Castillo Ambulante',
  'Ponyo',
  'El Servicio de Entregas de Kiki',
  'Nausicaä del Valle del Viento',
  'Porco Rosso',
  'La Tumba de las Luciérnagas',
  'El Cuento de la Princesa Kaguya',
  'Persépolis',
  'Akira',

  // Marvel / DC adicionales
  'Capitana Marvel',
  'Eternos',
  'Shang-Chi',
  'Daredevil',
  'Blade',
  'Venom',
  'X-Men',
  'Wolverine',
  'Hellboy',
  'Watchmen',
  'Kick-Ass',
  'Kingsman',
  'Linterna Verde',
  'The Flash',
  'Liga de la Justicia',
  'Shazam',
  'Escuadrón Suicida',
  'Aves de Presa',
  'El Hombre de Acero',
  'Superman',
  'Constantine',
  'Guerra Civil',
  'Guerra del Infinito',
  'Spider-Man: Lejos de Casa',
  'Spider-Man: Sin Camino a Casa',
  'Thor: Ragnarok',
  'Wonder Woman 1984',

  // James Bond / espías
  'Casino Royale',
  'Skyfall',
  'Spectre',
  'Sin Tiempo Para Morir',
  'GoldenEye',
  'Identidad Desconocida',

  // Acción / aventura
  'Búsqueda Implacable',
  'Los Mercenarios',
  '300',
  'Top Gun',
  'Top Gun: Maverick',
  'Tomb Raider',
  'Lara Croft: Cuna de la Vida',
  'Resident Evil',
  'Underworld',
  'Hitman',
  'Tropa de Élite',
  'Sicario: Tierra de Nadie',
  'La Estafa Maestra',
  'La Gran Evasión',
  'Atrápame si Puedes',
  'Black Hawk Derribado',
  'Francotirador',
  'Hasta el Último Hombre',
  'Robocop',
  'Aliens: El Regreso',
  'Terminator 2: El Juicio Final',
  'Duro de Matar',
  'Arma Mortal',
  'La Roca',
  'Cara a Cara',
  'Speed: Máxima Potencia',
  'Punto de Quiebre',

  // Crimen / Tarantino / clásicos
  'La Red Social',
  'Los Infiltrados',
  'Spotlight',
  'Snatch: Cerdos y Diamantes',
  'Buenos Muchachos',
  'Casino',
  'Heat',
  'Sospechosos de Siempre',
  'Perros de la Calle',
  'Kill Bill',
  'Bastardos sin Gloria',
  'Django sin Cadenas',
  'Había una Vez en Hollywood',
  'Los Odiosos Ocho',
  'Cara Cortada',
  'El Gran Lebowski',
  'Sin City',
  'Drive',
  'Chinatown',
  'La Naranja Mecánica',

  // Sci-Fi
  'Star Trek',
  '2001: Odisea del Espacio',
  'Ex Machina',
  'Her',
  'Distrito 9',
  'Snowpiercer: Expreso del Apocalipsis',
  'Looper',
  'Al Filo del Mañana',
  'Yo, Robot',
  'Sentencia Previa',
  'El Vengador del Futuro',
  'Vanilla Sky',
  'El Sexto Sentido',
  'Señales',
  'La Llegada',
  'Marte: Operación Rescate',
  'Gravedad',
  'Dune',
  'Dune Parte Dos',
  'Pasajeros',
  'Doce Monos',
  'El Curioso Caso de Benjamin Button',

  // Star Wars saga
  'El Imperio Contraataca',
  'El Retorno del Jedi',
  'La Amenaza Fantasma',
  'El Despertar de la Fuerza',
  'Rogue One',

  // Horror / suspenso
  'Pesadilla en Elm Street',
  'Viernes 13',
  'Scream: Vigila Quién Llama',
  'El Silencio de los Inocentes',
  'Los Otros',
  'El Aro',
  'El Conjuro',
  'Annabelle',
  'La Monja',
  'Insidious',
  'Get Out',
  'Midsommar',
  'Hereditary',
  'Un Lugar en Silencio',
  'Bird Box: A Ciegas',
  'La Cosa',
  '28 Días Después',
  'Carrie',
  'Misery',
  'La Llorona',
  'El Hoyo',
  'REC',
  'El Orfanato',
  'Tesis',
  'Abre los Ojos',
  'Verónica',
  'Sinister',
  'La Cabaña del Terror',
  'Cementerio de Animales',
  'Cisne Negro',
  'Réquiem por un Sueño',

  // LATAM / Argentina / Colombia / México
  'La Ciénaga',
  'El Aura',
  'Pizza, Birra, Faso',
  'Iluminados por el Fuego',
  'Tiempo de Valientes',
  'El Robo del Siglo',
  'Argentina, 1985',
  'La Sociedad de la Nieve',
  'Esperando la Carroza',
  'Comodines',
  'Tesis sobre un Homicidio',
  'Plata Quemada',
  'Un Cuento Chino',
  'La Estrategia del Caracol',
  'María Llena Eres de Gracia',
  'Pájaros de Verano',
  'Monos',
  'La Vendedora de Rosas',
  'Rosario Tijeras',
  'Como Agua para Chocolate',
  'Cronos',
  'El Espinazo del Diablo',
  'La Forma del Agua',
  'Pacific Rim',
  'Carancho',
  'El Estudiante',
  'El Mismo Amor, La Misma Lluvia',
  'Wakolda',
  'Las Acacias',
  'El Clan',
  'Animal',
  'Granizo',

  // España / Almodóvar / Amenábar
  'Mujeres al Borde de un Ataque de Nervios',
  'Átame',
  'La Piel que Habito',
  'Hable con Ella',
  'Tacones Lejanos',
  'Carne Trémula',
  'La Mala Educación',
  'Madres Paralelas',
  'Dolor y Gloria',
  'Ágora',
  'Memorias del Subdesarrollo',
  'Fresa y Chocolate',

  // Recientes (2020-2025)
  'Barbie',
  'Oppenheimer',
  'Pobres Criaturas',
  'Asesinos de la Luna',
  'Los Que Se Quedan',
  'Cónclave',
  'Bullet Train',
  'Knives Out: Entre Navajas y Secretos',
  'Glass Onion',
  'El Caballero Oscuro: La Leyenda Renace',

  // Comedia
  '¿Y Dónde Está el Piloto?',
  '¿Qué Pasó Ayer?',
  'Sucedió en Manhattan',
  'Una Historia del Bronx',
  'Hitch: Especialista en Citas',
  'Click: Perdiendo el Control',
  'Son Como Niños',
  'Una Guerra de Película',
  'Zoolander',
  'El Reportero',
  'Old School',
  'De Boda en Boda',
  'Una Pareja Despareja',
  'Mira Quién Habla',
  'Quisiera Ser Grande',
  'Cazafantasmas',
  'Hombres de Negro',
  'Una Noche en el Museo',
  'Stuart Little',
  'Beethoven: Uno Más de la Familia',
  'Las Tortugas Ninja',
  'Mejor Imposible',
  'Atrapado en el Tiempo',
  'El Show de Truman',
  'Náufrago',

  // Romance / Drama / Música
  'Cuatro Bodas y un Funeral',
  'Notting Hill',
  'Love Actually',
  'Mientras Dormías',
  'Cómo Perder a un Hombre en 10 Días',
  '10 Cosas que Odio de Ti',
  '(500) Días con Ella',
  'Crazy Stupid Love',
  'Antes del Amanecer',
  'Antes del Atardecer',
  'Yo Antes de Ti',
  'Rocketman',
  'Steve Jobs',
  'El Aviador',
  'Una Mente Brillante',
  'La Teoría del Todo',
  'El Código Enigma',
  'Johnny y June',
  'Ray',
  'Selena',
  'Whiplash: Música y Obsesión',
  'Birdman',
  'El Renacido',
  'El Gran Hotel Budapest',
  'Wicked',
  'Cats',
  'El Fantasma de la Ópera',

  // Guerra / histórico / clásicos
  'El Cazador',
  'Buenos Días Vietnam',
  'Cartas desde Iwo Jima',
  'Banderas de Nuestros Padres',
  'Nacido el 4 de Julio',
  'Lo Que el Viento se Llevó',
  'Casablanca',
  'Lawrence de Arabia',
  'Patton',
  '12 Años de Esclavitud',
  'El Mago de Oz',
  'Vértigo',
  'Los Pájaros',
  'La Ventana Indiscreta',
  'Con la Muerte en los Talones',
  '12 Hombres Sin Piedad',
  'Cantando Bajo la Lluvia',
  'Desayuno en Tiffany\'s',
  'Bonnie y Clyde',

  // Familia / Navidad / Aventura
  'Expreso Polar',
  'Buddy el Elfo',
  'Crónicas de Navidad',
  'El Grinch',
  'La Princesa Prometida',
  'Jumanji',
  'Jumanji: En la Selva',
  'Karate Kid',
  'Cool Runnings: Pasta Caliente',
  'Space Jam',
  'Un Sueño Posible',
  'Coach Carter',
  'Slumdog Millionaire',
  'El Discurso del Rey',
  'Memorias de un Geisha',
  'El Diario de la Princesa',
  'Boyhood: Momentos de una Vida',
  'Manchester Junto al Mar',
  'Lady Bird',
  'Moonrise Kingdom',
  'Los Tenenbaums',
  'El Árbol de la Vida',
  'La Vida Acuática',

  // Cult / 80s-90s / indie
  'Edward Manos de Tijera',
  'Beetlejuice',
  'Los Goonies',
  'Gremlins',
  'La Máscara',
  'Mentiroso Mentiroso',
  'Eterno Resplandor de una Mente sin Recuerdos',
  'Donnie Darko',
  'Petróleo Sangriento',
  'Lost in Translation',
  'Babe: El Chanchito Valiente',
  'Todo en un Día',
  'El Club de los Cinco',
  'Ace Ventura: Detective de Mascotas',
  'Una Boda en Tiempos de Locura',
]
