export const movies = [
  'Titanic',
  'El Rey León',
  'Toy Story',
  'Coco',
  'Frozen',
  'Buscando a Nemo',
  'Shrek',
  'Avatar',
  'Matrix',
  'El Padrino',
  'Volver al Futuro',
  'Jurassic Park',
  'Forrest Gump',
  'El Señor de los Anillos',
  'Harry Potter',
  'Star Wars',
  'Joker',
  'Batman',
  'El Hombre Araña',
  'Iron Man',
  'Los Vengadores',
  'Capitán América',
  'Thor',
  'La Mujer Maravilla',
  'Encanto',
  'Moana',
  'Intensamente',
  'Cars',
  'Ratatouille',
  'WALL-E',
  'Los Increíbles',
  'Monsters Inc',
  'Up',
  'La Bella y la Bestia',
  'La Sirenita',
  'Aladdín',
  'Cenicienta',
  'Mulán',
  'El Libro de la Selva',
  'Roma',
  'Amores Perros',
  'Y Tu Mamá También',
  'El Laberinto del Fauno',
  'Relatos Salvajes',
  'El Secreto de sus Ojos',
  'Nueve Reinas',
  'Diarios de Motocicleta',
  'Ciudad de Dios',
  'Bohemian Rhapsody',
  'Rápidos y Furiosos',
]
