export const movies = [
  'Titanic',
  'El Rey León',
  'Toy Story',
  'Coco',
  'Frozen',
  'Buscando a Nemo',
  'Shrek',
  'Avatar',
  'Matrix',
  'El Padrino',
  'Volver al Futuro',
  'Jurassic Park',
  'Forrest Gump',
  'El Señor de los Anillos',
  'Harry Potter',
  'Star Wars',
  'Joker',
  'Batman',
  'El Hombre Araña',
  'Iron Man',
  'Los Vengadores',
  'Capitán América',
  'Thor',
  'La Mujer Maravilla',
  'Encanto',
  'Moana',
  'Intensamente',
  'Cars',
  'Ratatouille',
  'WALL-E',
  'Los Increíbles',
  'Monsters Inc',
  'Up',
  'La Bella y la Bestia',
  'La Sirenita',
  'Aladdín',
  'Cenicienta',
  'Mulán',
  'El Libro de la Selva',
  'Roma',
  'Amores Perros',
  'Y Tu Mamá También',
  'El Laberinto del Fauno',
  'Relatos Salvajes',
  'El Secreto de sus Ojos',
  'Nueve Reinas',
  'Diarios de Motocicleta',
  'Ciudad de Dios',
  'Bohemian Rhapsody',
  'Rápidos y Furiosos',
  'Buscando a Dory',
  'Soul',
  'Luca',
  'Valiente',
  'Enredados',
  'Ralph el Demoledor',
  'Grandes Héroes',
  'Zootopia',
  'Red',
  'Lightyear',
  'Pinocho',
  '101 Dálmatas',
  'Dumbo',
  'Bambi',
  'Tiempos Violentos',
  'El Origen',
  'Interestelar',
  'Tenet',
  'Memento',
  'El Caballero de la Noche',
  'Blade Runner',
  'El Octavo Pasajero',
  'Depredador',
  'Terminator',
  'Mad Max',
  'Doctor Strange',
  'Viuda Negra',
  'Hulk',
  'Ant-Man',
  'Deadpool',
  'Guardianes de la Galaxia',
  'Pantera Negra',
  'Aquaman',
  'James Bond',
  'Misión Imposible',
  'John Wick',
  'Transformers',
  'Indiana Jones',
  'E.T. el Extraterrestre',
  'Tiburón',
  'Psicosis',
  'El Exorcista',
  'El Resplandor',
  'Halloween',
  'El Juego del Miedo',
  'It',
  'Mi Pobre Angelito',
  'Loco por Mary',
  'Una Esposa de Mentira',
  'Ricky Bobby',
  'Diario de una Pasión',
  'Crepúsculo',
  '50 Sombras de Grey',
  'Bridget Jones',
  'Mujer Bonita',
  'Ghost',
  'Dirty Dancing',
  'Anastasia',
  'El Príncipe de Egipto',
  'Madagascar',
  'La Era de Hielo',
  'Kung Fu Panda',
  'Cómo Entrenar a tu Dragón',
  'Río',
  'Hotel Transilvania',
  'La La Land',
  'Mamma Mia',
  'Grease',
  'Chicago',
  'Moulin Rouge',
  'Sonrisas y Lágrimas',
  'Rescatando al Soldado Ryan',
  'La Lista de Schindler',
  'El Pianista',
  'Apocalipsis Ahora',
  'Pelotón',
  '1917',
  'Dunkerque',
  'Rocky',
  'Million Dollar Baby',
  'Rambo',
  'El Viaje de Chihiro',
  'Mi Vecino Totoro',
  'La Princesa Mononoke',
  'Volver',
  'Todo Sobre mi Madre',
  'El Hijo de la Novia',
  'La Historia Oficial',
  'Camila',
  'Ocho Apellidos Vascos',
  'Coraline',
  'El Extraño Mundo de Jack',
  'Bichos',
  'Avengers: Endgame',
  'Logan',
  'Cuenta Conmigo',
  'La Vida es Bella',
  'Cinema Paradiso',
  'Amelie',
  'Trainspotting',
  'El Club de la Pelea',
  'Mar Adentro',
]
